exclude: 'build'

default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: end-of-file-fixer

-   repo: https://github.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        exclude: (clip/|trainers/vision_benchmark/|lpclip)
        args:
            - "--max-line-length=88"
            - "--ignore=E203,E501,W503,F401"

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.2.1
    hooks:
    -   id: pyupgrade
        args: ['--py36-plus']

-   repo: https://github.com/omnilib/ufmt
    rev: v1.3.0
    hooks:
    - id: ufmt
      additional_dependencies:
        - black == 21.9b0
        - usort == 0.6.4

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
    -   id: insert-license
        files: \.py$
        args:
        - --license-filepath
        - docs/license_header.txt
